Fri Feb 24 20:30:01 CST 2023
Empieza validaci√≥n de actualizaciones diarias\n
Cambiando nombre de archivos...
Descargando archivo nuevo...
Error: No such container: listado-postgres
Traceback (most recent call last):
  File "compare.py", line 168, in <module>
    actual = pd.read_csv(path_actual, index_col='id', keep_default_na=False)
  File "/home/vbass/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vbass/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/vbass/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/vbass/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/vbass/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
git add history.md changelog.md
git commit
git push
Proceso terminado!
