Wed Apr 27 20:30:01 CDT 2022
Empieza validaci√≥n de actualizaciones diarias

Cambiando nombre de archivos...
Descargando archivo nuevo...
Leyendo archivos...
Comparando archivos...
Traceback (most recent call last):
  File "compare.py", line 136, in <module>
    main()
  File "compare.py", line 134, in main
    compareFiles(actual,anterior,paths.path_history,paths.path_changelog)
  File "compare.py", line 29, in compareFiles
    history = open(path_history,'a')
FileNotFoundError: [Errno 2] No such file or directory: '/home/vbass/etiquetas/etiquetas/graphql-server/history.txt'
cp: cannot stat '/home/vbass/etiquetas/etiquetas/graphql-server/history.txt': No such file or directory
cp: cannot stat '/home/vbass/etiquetas/etiquetas/graphql-server/changelog.txt': No such file or directory
git add history.md changelog.md
git commit
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
	modified:   scripts/logEstatus.txt
	modified:   scripts/logfile.txt

Untracked files:
	Zacatuche.sh
	__pycache__/
	actualizaciones_agro.sh
	agro_actual.csv
	agro_anterior.csv
	comparaZacatuche.csv
	compare.py
	compareZacatuche.sh
	estatus.py
	functions.py
	paths.py
	pruebas.sh

no changes added to commit
git push
To github.com:CONABIO/catalogo-agrobiodiversidad.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:CONABIO/catalogo-agrobiodiversidad.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Proceso terminado!
